[project]
name = "1_decorator_cliapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.7.0",
    "langchain>=1.0.5",
    "langchain-aws>=1.0.0",
    "langgraph>=1.0.3",
    "mlflow>=3.6",
]
